# Generated by Django 2.1.4 on 2018-12-21 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20181221_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='registration_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
