bedroom_choices = {
  '1': 1,
  '2': 2,
  '3': 3,
  '4': 4,
  '5': 5,
  }

price_choices = {
  '100000': 'Rs 100,000',
  '200000': 'Rs 200,000',
  '300000': 'Rs 300,000',
  '400000': 'Rs 400,000',
  '500000': 'Rs 500,000',
  '600000': 'Rs 600,000',
  '700000': 'Rs 700,000',
  '800000': 'Rs 800,000',
  '900000': 'Rs 900,000',
  '1000000': 'Rs 1M+',
}

state_choices = {
        'Andaman and Nicobar Islands': 'AN',
        'Andhra Pradesh': 'AP',
        'Assam': 'AS',
        'Bihar': 'BR',
        'Chandigarh': 'CH',
        'Chhattisgarh': 'CT',
        'Dadra and Nagar Haveli': 'DN',
        'Daman and Diu': 'DD',
        'Delhi Pradesh': 'DL',
        'Goa': 'GA',
        'Gujarat': 'GJ',
        'Haryana': 'HR',
        'Himachal Pradesh': 'HP',
        'Jammu and Kashmir': 'JK',
        'Jharkhand': 'JH',
        'Karnataka': 'KA',
        'Kerala': 'KL',
        'Lakshadweep': 'LD',
        'Madhya Pradesh': 'MP',
        'Maharashtra': 'MH',
        'Manipur': 'MN',
        'Meghalaya': 'ML',
        'Mizoram': 'MZ',
        'Nagaland': 'NL',
        'Odisha, Orissa': 'OR',
        'Puducherry': 'PY',
        'Punjab': 'PB',
        'Rajasthan': 'RJ',
        'Sikkim': 'SK',
        'Tamil Nadu ': 'TN',
        'Telangana': 'TG',
        'Tripura': 'TR',
        'Uttar Pradesh': 'UP',
        'Uttarakhand,Uttaranchal': 'UT',
        'West Bengal': 'WB',
}