# Generated by Django 2.1.4 on 2018-12-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_auto_20181222_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='bathrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='bedrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
