# Generated by Django 2.1.4 on 2018-12-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_auto_20181224_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='photo_5',
            field=models.ImageField(blank=True, default='/media/images/defaults/default_property.jpeg', upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='photo_6',
            field=models.ImageField(blank=True, default='/media/images/defaults/default_property.jpeg', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
