# Generated by Django 2.1.4 on 2018-12-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_auto_20181225_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='photo_1',
            field=models.ImageField(blank=True, default='/media/defaults/default_property.jpeg', upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='photo_2',
            field=models.ImageField(blank=True, default='/media/defaults/default_property.jpeg', upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='photo_3',
            field=models.ImageField(blank=True, default='/media/defaults/default_property.jpeg', upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='photo_4',
            field=models.ImageField(blank=True, default='/media/defaults/default_property.jpeg', upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='photo_5',
            field=models.ImageField(blank=True, default='/media/defaults/default_property.jpeg', upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='photo_6',
            field=models.ImageField(blank=True, default='/media/defaults/default_property.jpeg', upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='photo_main',
            field=models.ImageField(blank=True, default='/media/defaults/default_property.jpeg', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
